# ==========================================================================================
# IMPORTANT: Replace ALL placeholder values ("YOUR_...") with the corresponding values 
# from your downloaded Firebase Service Account JSON file. 
# Ensure the private key is enclosed in single quotes.
# ==========================================================================================

# Standard Service Account Fields
type = "service_account"
project_id = "middleman-bccle" # Assuming this is your project ID
private_key_id = "YOUR_PRIVATE_KEY_ID_HERE"
private_key = '-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_CONTENT_HERE\n-----END PRIVATE KEY-----\n'
client_email = "YOUR_CLIENT_EMAIL_HERE"
client_id = "YOUR_CLIENT_ID_HERE"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "YOUR_CLIENT_X509_CERT_URL_HERE"
universe_domain = "googleapis.com"

# The streamlit_app.py file now looks for these individual keys instead of 'textkey'.
# If you run into a KeyError again, the error message will now tell you exactly 
# which individual key is missing.
